# 创建DNS服务相关配置文件
mkdir -p "${PROJECTHOME}"/dns
if [ -f "${PROJECTHOME}"/dns/dnsmasq.conf ]
then
   rm  "${PROJECTHOME}"/dns/dnsmasq.conf
fi

if [ -f "${PROJECTHOME}"/dns/resolv.conf ]
then
  rm  "${PROJECTHOME}"/dns/resolv.conf
fi

# 初始化dnsmasq.conf
echo >"${PROJECTHOME}"/dns/dnsmasq.conf EOF

EOF

# 初始化dnsmasq.conf
cat  >  "${PROJECTHOME}"/dns/dnsmasq.conf <<EOF
#dnsmasq config, for a complete example, see:
#  http://oss.segetech.com/intra/srv/dnsmasq.conf
#log all dns queries
log-queries
#dont use hosts nameservers
no-resolv
#use cloudflare as default nameservers, prefer 1^4
server=1.0.0.1
server=1.1.1.1
strict-order
##serve all .company queries using a specific nameserver
##explicitly define host-ip mappings
#server=/company/10.0.0.1
#我的DNS服务器
address=/MyDns/${DNSSERVICE}

EOF


# 初始化resolv.conf
cat >"${PROJECTHOME}"/dns/resolv.conf <<EOF
# Generated by NetworkManager
nameserver ${DNSSERVICE}

EOF