

version: '3.0'

networks:
  net_n9e:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNETWORK}

services:
  dns-server:
    container_name: n9e-dns
    image: 'jpillora/dnsmasq'
    restart: always
    networks:
      net_n9e:
        ipv4_address: ${DNS_SERVICE}
    environment:
      - TZ=Asia/Shanghai
      - HTTP_USER=${DNS_USER}
      - HTTP_PASS=${DNS_PASSWD}
    ports:
      - 53:53/udp
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/dns/dnsmasq.conf:/etc/dnsmasq.conf:rw


  timescaledb:
    image: xiaochouyou/promscale-extension:0.6.0-ts2.7.2-pg14
    container_name: n9e-timescaledb
    restart: always
    networks:
      net_n9e:
        ipv4_address: ${POSTGRES_SERVICE}
    environment:
      - csynchronous_commit=off
      - POSTGRES_PASSWORD=${POSTGRES_PASSWD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
      # promscale
      - 9201:9201
      - 9202:9202
      # prometheus
      - 9090:9090
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/timescaledb/data:/var/lib/postgresql/data:rw
    mem_limit: 512m
    depends_on:
      - dns-server


  promscale:
    image: timescale/promscale:0.14
    container_name: n9e-promscale
    restart: always
    network_mode: container:n9e-timescaledb
    environment:
      - PROMSCALE_DB_HOST=${PROMSCALE_DB_HOST}
      - PROMSCALE_DB_PORT=${PROMSCALE_DB_PORT}
      - PROMSCALE_DB_SSL_MODE=allow
      - PROMSCALE_DB_NAME=${PROMSCALE_DB_NAME}
      - PROMSCALE_DB_USER=${PROMSCALE_DB_USER}
      - PROMSCALE_DB_PASSWORD=${PROMSCALE_DB_PASSWORD}
      - WAIT_HOSTS=dns-server:8080,timescaledb:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
    mem_limit: 512m
    depends_on:
      - dns-server
      - timescaledb


  prometheus:
    image: xiaochouyou/prometheus:v2.33.4
    container_name: n9e-prometheus
    restart: always
    network_mode: container:n9e-timescaledb
    environment:
      - WAIT_HOSTS=dns-server:8080,promscale:9201
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/prometheus/data:/prometheus:rw
      - ${PROJECTHOME}/prometheus/etc:/etc/prometheus:rw
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=45d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--query.lookback-delta=2m'
      - '--enable-feature=remote-write-receiver'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    mem_limit: 512m
    stop_grace_period: 10s
    depends_on:
      - promscale
      - dns-server
      - timescaledb

  redis:
    image: xiaochouyou/redis:6.2
    container_name: n9e-redis
    restart: always
    networks:
      net_n9e:
        ipv4_address: ${REDIS_SERVICE}
    ports:
      - "6379:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/redis/data:/data:rw
    command:
      - 'redis-server'
      - '/data/redis.conf'
    mem_limit: 512m
    depends_on:
      - dns-server

  mysql:
    platform: linux/x86_64
    image: xiaochouyou/mysql:5.7
    container_name: n9e-mysql
    restart: always
    networks:
      net_n9e:
        ipv4_address: ${MYSQL_SERVICE}
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/mysql/data:/var/lib/mysql/
      - ${PROJECTHOME}/mysql/initsql:/docker-entrypoint-initdb.d/
      - ${PROJECTHOME}/mysql/etc:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - dns-server


  ibex:
    image: ulric2019/ibex:0.3
    container_name: n9e-ibex-server
    hostname: ibex
    restart: always
    networks:
      net_n9e:
        ipv4_address: ${IBEX_SERVICE}
    ports:
      - "10090:10090"
      - "20090:20090"
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/ibex/etc:/app/etc
    mem_limit: 512m
    depends_on:
      - dns-server
      - mysql
    command: >
      sh -c "/wait && /app/ibex server"


  n9eserver:
    image: flashcatcloud/nightingale:5.12.1
    container_name: n9e-n9eserver
    restart: always
    networks:
      net_n9e:
        ipv4_address: ${N9E_SERV_SERVICE}
    ports:
      - "19000:19000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/n9e/etc:/app/etc
    mem_limit: 512m
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306, redis:6379
    depends_on:
      - mysql
      - redis
      - prometheus
      - ibex
    command: >
      sh -c "/wait && /app/n9e server"


  n9ewebapi:
    image: flashcatcloud/nightingale:5.12.1
    container_name: n9e-n9ewebapi
    restart: always
    networks:
      net_n9e:
        ipv4_address: ${N9E_WEB_SERVICE}
    ports:
      - "18000:18000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/n9e/etc:/app/etc
    mem_limit: 512m
    environment:
      GIN_MODE: release
      TZ: Asia/Shanghai
      WAIT_HOSTS: mysql:3306, redis:6379
    depends_on:
      - mysql
      - redis
      - prometheus
      - ibex
    command: >
      sh -c "/wait && /app/n9e webapi"


  categraf:
    image: flashcatcloud/categraf:v0.2.13
    container_name: n9e-categraf
    restart: always
    networks:
      net_n9e:
        ipv4_address: ${CATEGRAF_SERVICE}
    mem_limit: 512m
    environment:
      TZ: Asia/Shanghai
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_MOUNT_PREFIX: /hostfs
    ports:
      - "9100:9100/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/categraf/conf:/etc/categraf/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs
    depends_on:
      - n9eserver


  draw:
    image: xiaochouyou/drawio:20.4.0
    container_name: n9e-drawio
    restart: always
    networks:
      net_n9e:
        ipv4_address: ${DRAWIO_SERVICE}
    mem_limit: 512m
    ports:
      - 8081:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/drawio/conf:/usr/local/tomcat/conf
      - ${PROJECTHOME}/drawio/webapps:/usr/local/tomcat/webapps
    depends_on:
      - dns-server


  grafana9:
    image: xiaochouyou/grafana:9.1.7
    container_name: n9e-grafana-9
    networks:
      net_n9e:
        ipv4_address: ${GRAFANA_9_SERVICE}
    ports:
      - 3009:3000
    mem_limit: 512m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/grafana9/etc:/etc/grafana
      - ${PROJECTHOME}/grafana9/lib:/var/lib/grafana
    depends_on:
      - dns-server

  grafana8:
    image: xiaochouyou/grafana:8.5.13
    container_name: n9e-grafana-8
    networks:
      net_n9e:
        ipv4_address: ${GRAFANA_8_SERVICE}
    ports:
      - 3008:3000
    mem_limit: 512m
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
      - ${PROJECTHOME}/grafana8/etc:/etc/grafana
      - ${PROJECTHOME}/grafana8/lib:/var/lib/grafana
    depends_on:
      - dns-server


#  nginx:
#    container_name: n9e-nginx
#    image: nginx
#    restart: always
#    networks:
#      net_n9e:
#        ipv4_address: ${NGINXSERVICE}
#    environment:
#      - NGINX_PORT=10080
#    ports:
#      - 10080:10080
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - ${PROJECTHOME}/dns/resolv.conf:/etc/resolv.conf:ro
#      - ${PROJECTHOME}/nginx/etc:/etc/nginx:rw
#      - ${PROJECTHOME}/nginx/html:/usr/share/nginx/html:rw
#      - ${PROJECTHOME}/nginx/logs:/var/log/nginx:rw
#    mem_limit: 512m
#    depends_on:
#      - dns-server
#

