FROM nginx:1.23.1-alpine

ENV PROC_UID  1000
ENV PROC_GID  1000

RUN (sed -i 's/nginx:x:101:nginx/nginx:x:'${PROC_GID}':nginx/g'  /etc/group )
RUN (sed -i 's/101:101/'${PROC_UID}':'${PROC_GID}'/g'  /etc/passwd )
RUN (chown -R nginx:nginx /etc/nginx )

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx","-g","daemon off;"]
