FROM timescaledev/promscale-extension:0.6.0-ts2.7.2-pg14
ARG PROC_GID=1000
ARG PROC_UID=1000
ARG N9E_USER_NAME=n9e
ARG N9E_DB_NAME=n9e
ARG N9E_DB_PASSWD=n9e


COPY 003_sed_n9e.sh /docker-entrypoint-initdb.d/
COPY 0022_init_n9e.sql /docker-entrypoint-initdb.d/


ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["postgres"]
