FROM prom/prometheus:v2.33.4
# 创建程序账号
ENV PROC_UID  1000
ENV PROC_GID  1000

USER root
COPY start.sh /
RUN ( chmod 777 /start.sh )

USER nobody
ENTRYPOINT ["/start.sh"]
CMD ["--config.file=/data/prometheus/etc/prometheus.yml" "--storage.tsdb.path=/data/prometheus/prometheus" "--web.console.libraries=/data/prometheus/share/console_libraries" "--web.console.templates=/data/prometheus/share/consoles"]

VOLUME [ "/data" ]