FROM jgraph/drawio:20.4.0

ARG PROC_GID=1000
ARG PROC_UID=1000

USER root
RUN (sed -i 's/472:/'${PROC_UID}':/g'  /etc/passwd )
RUN (chown -R grafana /var/lib/grafana/ /etc/grafana/ /usr/share/grafana /var/log/grafana )


ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["catalina.sh" "run"]
