FROM mysql:5.7
ARG PROC_GID=1000
ARG PROC_UID=1000


RUN (sed -i 's/mysql:x:999/mysql:x:'${PROC_GID}'/g'  /etc/group )
RUN (sed -i 's/999:999/'${PROC_UID}':'${PROC_GID}'/g'  /etc/passwd )
RUN (chown -R mysql:mysql /var/lib/mysql/ /etc/mysql )


ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["mysqld"]
