FROM grafana/grafana:8.5.13

ARG PROC_GID=1000
ARG PROC_UID=1000

USER root
RUN (sed -i 's/472:/'${PROC_UID}':/g'  /etc/passwd )
RUN (chown -R grafana /var/lib/grafana/ /etc/grafana/ /usr/share/grafana /var/log/grafana )
USER grafana
RUN (grafana-cli plugins install yesoreyeram-boomtheme-panel)
RUN (grafana-cli plugins install agenty-flowcharting-panel)
RUN (grafana-cli plugins install bilibala-echarts-panel)
RUN (grafana-cli plugins install volkovlabs-echarts-panel)
RUN (grafana-cli plugins install grafana-clock-panel)
RUN (grafana-cli plugins install grafana-singlestat-panel)
RUN (grafana-cli plugins install volkovlabs-image-panel)
ENTRYPOINT ["/run.sh"]
CMD ["/bin/sh"]
